# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Install Flux to cluster
  run_once: true
  changed_when: false
  ansible.builtin.command: "{{ flux_download_unarchive_dest }}/flux install --registry={{ flux_image_registry }}"
