namespace: atmosphere
name: common
version: 0.6.0
readme: README.md
authors:
  - Mohammed Naser <mnaser@vexxhost.com>
description: Set of common roles for deploying Kubernetes components
license:
  - Apache-2.0
dependencies:
  kubernetes.core: '>=2.4.0'
  vexxhost.kubernetes: '>=2.5.0'
tags:
  - application
  - cloud
  - infrastructure
  - linux
repository: https://github.com/vexxhost/atmosphere.common
documentation: https://github.com/vexxhost/atmosphere.common/tree/main/docs
homepage: https://github.com/vexxhost/atmosphere.common
issues: https://github.com/vexxhost/atmosphere.common/issues
