# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Deploy Helm chart
  run_once: true
  kubernetes.core.helm:
    name: "{{ external_secrets_operator_helm_release_name }}"
    chart_repo_url: "{{ external_secrets_operator_helm_repository_url }}"
    chart_ref: "{{ external_secrets_operator_helm_chart_name }}"
    chart_version: "{{ external_secrets_operator_helm_chart_version }}"
    release_namespace: "{{ external_secrets_operator_helm_release_namespace }}"
    create_namespace: true
    kubeconfig: "{{ external_secrets_operator_helm_kubeconfig }}"
    values: "{{ _external_secrets_operator_helm_values | combine(external_secrets_operator_helm_values, recursive=True) }}"

- name: Wait for 'external-secrets' deployment to be available
  run_once: true
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: "{{ external_secrets_operator_helm_release_name }}"
    namespace: "{{ external_secrets_operator_helm_release_namespace }}"
    kubeconfig: "{{ external_secrets_operator_helm_kubeconfig }}"
    wait_sleep: 5
    wait_timeout: 90
    wait: true
    wait_condition:
      type: Available
      status: true
