# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Deploy Helm chart
  run_once: true
  kubernetes.core.helm:
    name: "{{ metrics_server_helm_release_name }}"
    chart_repo_url: "{{ metrics_server_helm_repository_url }}"
    chart_ref: "{{ metrics_server_helm_chart_name }}"
    chart_version: "{{ metrics_server_helm_chart_version }}"
    release_namespace: "{{ metrics_server_helm_release_namespace }}"
    create_namespace: true
    kubeconfig: "{{ metrics_server_helm_kubeconfig }}"
    values: "{{ _metrics_server_helm_values | combine(metrics_server_helm_values, recursive=True) }}"
