# Copyright (c) 2026 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

glance_image_cloud: atmosphere

# glance_image_tempfile_path:
glance_image_url: ""
glance_image_oci_reference: ""
glance_image_oci_path: ""
glance_image_oci_sha512: ""
glance_image_oci_architecture: amd64
glance_image_oci_authfile: ""

glance_image_http_proxy: "{{ http_proxy | default('') }}"
glance_image_https_proxy: "{{ https_proxy | default('') }}"
glance_image_no_proxy: "{{ no_proxy | default('') }}"

glance_image_wait_for_api: true
glance_image_api_deployment_name: glance-api
glance_image_api_deployment_namespace: openstack
glance_image_retries: 60
