# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

_vault_operator_helm_values:
  image:
    repository: "{{ vault_operator_image | atmosphere.common.docker_image('name') }}"
    tag: "{{ vault_operator_image | atmosphere.common.docker_image('tag') }}"
  bankVaults:
    image:
      repository: "{{ vault_operator_bank_vaults_image | atmosphere.common.docker_image('name') }}"
      tag: "{{ vault_operator_bank_vaults_image | atmosphere.common.docker_image('tag') }}"
  nodeSelector: "{{ vault_operator_node_selector }}"
