# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

dependency:
  name: galaxy
  options:
    requirements-file: molecule/default/requirements-dev.yaml
driver:
  name: default
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  inventory:
    host_vars:
      instance:
        kubeconfig_path: "$HOME/.kube/config"
        ansible_python_interpreter: ${ANSIBLE_PYTHON_INTERPRETER_OVERRIDE:-"/usr/bin/python3"}
verifier:
  name: ansible
