# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Deploy Helm chart
  run_once: true
  kubernetes.core.helm:
    name: "{{ dellhw_exporter_helm_release_name }}"
    chart_repo_url: "{{ dellhw_exporter_helm_repository_url }}"
    chart_ref: "{{ dellhw_exporter_helm_chart_name }}"
    chart_version: "{{ dellhw_exporter_helm_chart_version }}"
    release_namespace: "{{ dellhw_exporter_helm_release_namespace }}"
    create_namespace: true
    kubeconfig: "{{ dellhw_exporter_helm_kubeconfig }}"
    values: "{{ _dellhw_exporter_helm_values | combine(dellhw_exporter_helm_values, recursive=True) }}"
