# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

_external_secrets_operator_helm_values:
  global:
    nodeSelector: "{{ external_secrets_operator_node_selector }}"
  image:
    repository: "{{ external_secrets_operator_image | atmosphere.common.docker_image('name') }}"
    tag: "{{ external_secrets_operator_image | atmosphere.common.docker_image('tag') }}"
  leaderElect: true
  certController:
    create: false
  webhook:
    create: false
  concurrent: 100
  extraArgs:
    client-burst: 100
    client-qps: 50
    store-requeue-interval: 1m0s
