# Copyright (c) 2022 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Deploy secretgen-controller
  kubernetes.core.k8s:
    state: present
    definition: >-
      {{ lookup('ansible.builtin.template', 'release.yml.tpl') | from_yaml_all | list }}
