# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: molecule-external-secret
  namespace: default
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: molecule
    kind: ClusterSecretStore
  target:
    name: molecule-secret
  data:
    - secretKey: foo
      remoteRef:
        key: molecule
        property: foo
