# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

dellhw_exporter_helm_repository_name: dellhw_exporter
dellhw_exporter_helm_repository_url: https://galexrt.github.io/dellhw_exporter
dellhw_exporter_helm_chart_name: dellhw_exporter
dellhw_exporter_helm_chart_version: 2.0.0-rc.1

dellhw_exporter_helm_release_namespace: dellhw-exporter
dellhw_exporter_helm_release_name: dellhw_exporter

dellhw_exporter_helm_values: {}

dellhw_exporter_image: quay.io/galexrt/dellhw_exporter:v{{ dellhw_exporter_helm_chart_version }}
