# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Deploy "external-secrets-operator"
  hosts: "{{ target | default('all') }}"
  gather_facts: false
  roles:
    - role: atmosphere.common.external_secrets_operator
      tags:
        - external-secrets-operator
